CurrentUser = ""
AccessLevel = "Player"
TeamFile = "teams.json"
UserFile = "data.json"
PlayerFile = "players.json"
MatchFile = "matches.json"
PlayerStatsFile = "playerStats.json"
UpdatesFile = "updates.json"
SeasonFile = "season.json"
BackupListFile = "BackUpList.json"
BackupDateFile = "BackupDates.json"
MatchReportFile = "matchReport.json"
MatchAvailablityFile = "matchAvailablity.json"
PagesViewed = ["Login"]

